[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tcpypi"
version = "1.3.5"
description = "tcpyPI: Tropical cyclone potential intensity calculations in Python"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE" }
authors = [
    { name = "Daniel M. Gilford, PhD", email = "dgilford@climatecentral.org" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "xarray>=0.16.2",
    "numba>=0.51.2",
    "numpy>=1.19.5"
]

[project.urls]
Homepage = "https://github.com/dgilford/tcpyPI"
Download = "https://github.com/dgilford/tcpyPI"

[tool.setuptools.package-data]
tcpyPI = ["data/sample_data.nc"]

[tool.setuptools.packages.find]
where = ["."]
